### ISSUE TITLE
Cannot configure frequency for YDLIDAR X4

### ISSUE THREAD

**Issue by simonrozsival** [YDLIDAR/ydlidar_ros#1]
Hi! I'm trying to achieve the 12 Hz frequency for the X4 lidar. I checked the code and discovered, that the frequency is not changed for X4 as there is an if statement which checks the model and X4 is not one of the "supporrted" ones. I tried changing the code myself but I can't get it to work. 

Can you please document somewhere what are the necessary steps to achieve 12 Hz rotation with X4? Thanks!

**Comment by simonrozsival** [comment]
Would it be possible to get any kind of response, @yangfuyuan? I suppose the hardware does not allow different frequencies despite it being advertised as such, or does it?

**Comment by yangfuyuan** [comment]
X4 Lidar needs to be adjuested by pwm, your external pwm to the lidar to speed.

**Comment by simonrozsival** [comment]
OK. I'll try that. Thanks for the response.
