### ISSUE TITLE
ydlidar x2 health error

### ISSUE THREAD

**Issue by hj2222** [YDLIDAR/ydlidar_ros#3]
my ydlidar x2 doesn't work

when i plug the cable, motor is working but i got error health code ffffffff 

i configured baud rate 115200, idk why this error comes

plz let me know, thanks

**Comment by CtfChan** [comment]
Same issue here.

**Comment by CtfChan** [comment]
Download the ros.zip in the X2 section of the official website. There's a ros driver in that file that works.

**Comment by JiahengZhao** [comment]
> Download the ros.zip in the X2 section of the official website. There's a ros driver in that file that works.

Same issue. Did you download ROS.zip in the X4 section? Because I only saw ros.pdf at X2. And even use the zip file in X4 the error still occurred...

**Comment by JiahengZhao** [comment]
Hey there, everything works well when I checkout X2 branch....

**Comment by esf2468** [comment]
> X2 지점을 체크 아웃하면 모든 것이 잘 작동합니다 ....

How can I checkout a branch? 
Please help me
