### ISSUE TITLE
Name of scan topic not configurable

### ISSUE THREAD

**Issue by lukas-bernhard** [YDLIDAR/ydlidar_ros#4]
Please add a ROS parameter for changing the name of the scan topic. Right now it is not possible to properly use multiple nodes at the same time, since they all publish to the same topic with the hard-coded name "scan".

**Comment by ruehr** [comment]
You can always remap the topic in your launch file:
G4.launch:

```
  <node name="ydlidar_node"  pkg="ydlidar_ros"  type="ydlidar_node" output="screen" respawn="false" >
    <remap from="scan" to="scan_a"/>
..
```

**Comment by lukas-bernhard** [comment]
Thank you! My bad for not realizing that... Appreciate the hint.
