### ISSUE TITLE
ydlidar_node.cpp has a compile error.

### ISSUE THREAD

**Issue by KMiyawaki** [YDLIDAR/ydlidar_ros#7]
When I executed catkin_make with the latest version of the master branch, I had a following comile error.

```shell
/home/oit/catkin_ws/src/ydlidar_ros/src/ydlidar_node.cpp: In function ‘int main(int, char**)’:
/home/oit/catkin_ws/src/ydlidar_ros/src/ydlidar_node.cpp:118:5: error: expected ‘;’ before ‘laser’
     laser.setSingleChannel(isSingleChannel);
```

That will be fixed by adding a semicolon at the end of the line 117.
https://github.com/YDLIDAR/ydlidar_ros/blob/c9fddf94c6aaee158d26367e700d8d0a7dde2442/src/ydlidar_node.cpp#L117

**Comment by yangfuyuan** [comment]
thank you
