### ISSUE TITLE
New X2L start to spin with laser one just connect it to USB

### ISSUE THREAD

**Issue by FPSychotic** [YDLIDAR/ydlidar_ros#9]
Hi, I have a X4 , and got a x2l due to size. The X2L will start to work, spin and laser with just connect it to a USB, doesn't matter if data or power usb, I will start to spin, is this a normal behaviour, I dont think so and my X4 works only when you activate it by software.

**Comment by itsmariodias** [comment]
I have the same issue. Can you guys please confirm this? Seems the default state is max speed instead of off.

**Comment by FPSychotic** [comment]
They told me it was designed like that. I don't know who was the genius. Apart it makes vibration and oscillation when working in the whole robot, close to unusable.
X4 is OK, but X2L is rubbish, just the size is ok

**Comment by itsmariodias** [comment]
Jeez that sucks. Might have to to manually work around it then. Thanks for letting me know.

**Comment by openbsod** [comment]
>  .. vibration ..close to unusable

I second this.
